### PR TITLE
rename from ApiApprover to PublicApiGenerator

### PR DESCRIPTION
**Pull request by adamralph**
Before merging, the org and repo should both be renamed to "PublicApiGenerator".

Also, the description displayed on the repo home page ("Simple project to approve the public API of a project (useful for semantic versioning)") should be altered and the "website"  (http://jake.ginnivan.net/apiapprover) should probably be altered or cleared.

### CODE REVIEW

**Comment by sungam3r** [comment]
Good suggestion.

**Comment by adamralph** [comment]
@danielmarbach I see you've renamed the repo, but please note that some of the links in the code will 404 until the org is also renamed. E.g. https://github.com/ApiApprover/PublicApiGenerator/blob/8e9dde8edd020a2673ab68557112c253a5eb157e/src/Directory.Build.props#L5

**Comment by danielmarbach** [comment]
Thanks @adamralph . Yes I'm aware of that. I just didn't rename the org yet. It is done now

**Comment by sungam3r** [comment]
I just got 404 while watching PR. :)

**Pull request merged**
